#import "@preview/saar-lst-thesis:0.1.0": *
#import "@preview/pergamon:0.8.0": *


// Change to "de" for German template labels.
#set text(lang: "en")

// Fill in your thesis metadata here. The final `doc` argument tells the
// template where to place the thesis body written below this block.
#show: doc => lst(
  title: [Analysing Syntactic Long-term Alignment in Large Language Models],
  author: [Florian Kandra],
  matriculation-number: [12345],
  supervisors: (
    ([Supervisors], [Prof. Dr. Alexander Koller], [Prof. Dr. Vera Demberg]),
    ([Additional advisor], [Dr. Michael Sullivan])
  ),
  date: [31.12.2024],

  abstract: [
    This thesis explores the effects of long-term syntactic alignment in Large Language Models
    (LLMs). An approach by Reitter (2008) was adapted to analyze alignment effects between
    speakers. The analysis replicates previous findings from Reitter & Moore and was validated
    against baseline data. Additionally, new datasets created with OpenAI’s GPT-4o provide a
    basis for analyzing conversational texts generated by LLMs, addressing a gap in existing
    research for evaluating LLM-generated texts.

    The findings reveal that syntactic alignment occurs in LLMs over extended periods. A second
    analysis further explores how the process of alignment evolves throughout a conversation,
    showing that LLMs consistently adjust their syntax, with the largest changes occurring early
    on.

    These results indicate that LLMs are not only influenced by the semantics of instructions,
    but also by the syntax present in their context. LLM responses are shaped not only by the
    vector representations of tokens in their prompts, but also by the linear order in which those
    tokens appear.
  ],

  acknowledgments: [
    First and foremost, I want to thank my incredible supervisors, Prof. Dr. Koller and Prof. Dr.
    Demberg, who guided me throughout an extended period and provided support no matter
    where I was. Your thoughtful and precise feedback was crucial, always helping me to spot the
    next steps. Thank you for your enduring support and all the lively discussions along the way!

    I also want to give a special shoutout to my friends, especially Felix Cagliotti, who took the
    time for long brainstorming sessions despite his busy schedule. Your early-stage support and
    creative ideas were a great way to get started!

    To my flatmates -- thank you for taking time off me by reducing my cooking workload. And
    to my family -- thank you for baring me as the hermit that I was, especially during Christmas
    time. A big thanks to my dad for always being there to discuss my research challenges, my
    brother for his incredibly quick and spot-on ideas and my mom for keeping my mind light
    and stress-free.

    Lastly, a big hug to our cat Minka, who somehow managed to stay with us through at least
    half of my work -- offering purrs and cuddles when I needed them most!
  ],

  doc
)


// Put your BibTeX entries in custom.bib and cite them with #cite("key").
#add-bib-resource(read("custom.bib"))

// This helper only creates placeholder figure boxes for the sample document.
// Remove it in a real thesis and use #figure(...) with your actual images,
// tables, or diagrams.
#let sample-figure(title, body) = box(
  width: 100%,
  inset: 1.1em,
  fill: luma(248),
  stroke: (paint: luma(215), thickness: 0.6pt),
)[
  #align(center)[
    #text(font: "Open Sans", weight: "bold", size: 12pt)[#title]
    #v(0.4em)
    #text(size: 10pt)[#body]
  ]
]


= Introduction <sec:introduction>

Large language models are commonly evaluated by asking whether they solve tasks, follow
instructions, or provide useful answers. This thesis takes a complementary perspective. It asks
whether the form of a model's language is shaped by the form of the language that precedes it.
In particular, I study syntactic long-term alignment: the tendency of a system to reuse,
avoid, or gradually drift toward syntactic patterns that appeared earlier in a dialogue.

The phenomenon is familiar from human conversation. Speakers often converge on similar
lexical choices, comparable referring expressions, and parallel syntactic frames. Such alignment
is rarely perfect copying. It is better understood as a pressure on the distribution of choices
available to a speaker. If one participant repeatedly uses a relative clause or a passive
construction, the other participant may become slightly more likely to use the same kind of
construction later.

For language models, this question is both practical and theoretical. It is practical because many
applications place models in long conversations, tutoring sessions, editing workflows, or
interactive coding environments. In those settings, syntactic drift can change the perceived
style of the assistant. It is theoretical because alignment effects give us a way to ask how much
of a model's behavior is driven by abstract task instructions and how much is driven by the
surface form of the prompt. This distinction echoes broader debates about form, meaning, and
understanding in neural language systems #cite("bender-koller-2020-climbing").


The rest of the thesis is organized as follows. Chapter 2 reviews syntactic alignment in human
dialogue and summarizes related work on formal syntax and model evaluation. Chapter 3
introduces the datasets and the annotation pipeline. Chapter 4 presents the main alignment
experiments. Chapter 5 discusses qualitative patterns, limitations, and implications for prompt
design.

= Background

The study of alignment begins with the observation that dialogue is coordinated at many
levels. Participants coordinate topics, turn boundaries, referring expressions, lexical choices,
and grammatical forms. This coordination reduces effort: once a construction has been used, it
becomes easier for both speakers to reuse it. Psycholinguistic work often explains this with
priming, shared representations, or interactive alignment mechanisms.

In computational settings, alignment is harder to define. A language model has no stable
communicative intention in the human sense. It samples or selects continuations from a
distribution conditioned on context. Nevertheless, the output distribution can reflect structural
properties of earlier text. If a prompt contains many subordinate clauses, later responses may
become more likely to contain subordinate clauses as well.

The difficulty is that surface similarity can be misleading. Two responses may both contain
long sentences without sharing a syntactic construction. Conversely, two responses can differ
lexically while sharing an abstract dependency pattern. For this reason, the experiments in this
thesis use parsed representations rather than raw string overlap.

== Related Work

Syntactic priming has been studied extensively in human production. Classic experiments show
that speakers are more likely to reuse a syntactic frame after hearing or producing it. The effect
has been observed in dialogue, picture description, and sentence completion tasks. It is usually
small but reliable, and it interacts with lexical repetition, semantic similarity, and discourse
context.

Work on neural language models has focused more often on semantic consistency,
instruction-following, and factuality. However, several strands of research are relevant here.
Prompt sensitivity studies show that small changes in wording can change model behavior.
Style transfer and persona consistency studies show that models can preserve surface features
across a generation. Long-context evaluations show that models can retrieve and reuse details
from earlier passages.

The analysis also draws on formal accounts of grammar. Combinatory Categorial Grammar is
one example of a framework in which lexical entries and combinatory rules jointly determine
the space of possible derivations #cite("kuhlmann-etal-2015-lexicalization"). The experiments
below do not implement a CCG parser, but the general point is important: syntactic form is not
merely a string-level property. It involves structured dependencies that must be approximated
carefully when measured automatically.

#figure(kind: table, caption: [Summary of alignment-related phenomena.])[
  #table(
    columns: (1.5fr, 2.4fr, 1.4fr),
    inset: 6pt,
    table.header([Phenomenon], [Typical signal], [Timescale]),
    [Lexical reuse], [Repeated words or phrases], [Local to medium],
    [Syntactic priming], [Repeated abstract structures], [Local],
    [Style matching], [Register, sentence length, punctuation], [Medium],
    [Long-term alignment], [Persistent structural bias], [Medium to long],
  )
] <tab:phenomena>

= Data and Methods

The experiments use synthetic conversations designed to isolate syntactic form from semantic
content. Each conversation consists of a neutral task description, a context paragraph, and a
probe question. The context paragraph appears in one of two variants. The variants express the
same content but differ in the target construction. The probe question then asks for a response
that is semantically compatible with both variants.

This design makes it possible to compare responses across matched pairs. If the model sees the
passive-heavy variant, does it produce more passive clauses in the answer than when it sees the
active-heavy variant? If it sees a context with many relative clauses, does it produce more
relative clauses in a later explanation?

== Prompt Construction

Prompts were written in pairs. Each pair has a high-alignment condition and a low-alignment
condition. The high-alignment condition contains repeated instances of the target construction.
The low-alignment condition uses alternative constructions with the same propositional
content. The probe is identical across the pair.

For example, a passive condition might describe several observations as "the file was checked",
"the result was recorded", and "the summary was revised". The matched active condition would
use "the assistant checked the file", "the script recorded the result", and "the student revised
the summary". The final probe asks for an explanation of the procedure without mentioning
voice.

#figure(caption: [Schematic contrast between matched prompt variants.])[
  #sample-figure(
    [Variant A: active frames | Variant B: passive frames],
    [Both variants describe the same sequence of events. Only syntactic realization is changed.]
  )
] <fig:variants>

The prompts were also balanced for length. Exact equality is impossible because constructions
have different word counts, but the average difference between paired contexts was kept below
five percent. Pairs with larger differences were revised or removed.

== Target Constructions

The analysis focuses on four construction families: active-passive alternations, relative
clauses, complement clauses, and prepositional phrase sequences. These constructions were
chosen because they are common enough to appear naturally in generated text but structured
enough to be detected by a parser.

#figure(kind: table, caption: [Target constructions used in the experiments.])[
  #table(
    columns: (1.5fr, 2.4fr, 1.6fr),
    inset: 6pt,
    table.header([Construction], [Detection cue], [Example]),
    [Passive voice], [Auxiliary plus passive participle], [was revised],
    [Relative clause], [Relative marker with clausal dependent], [that failed],
    [Complement clause], [Clausal complement relation], [said that...],
    [PP sequence], [Two or more adjacent prepositional phrases], [in the file on Monday],
  )
] <tab:targets>

The parser labels are not perfect proxies for linguistic categories. For this reason, each
construction family is treated as a measurable approximation. The interpretation of results is
therefore conservative: a significant effect indicates a change in parser-detected structure, not
necessarily a complete linguistic theory of the model's syntax.

== Generation Protocol

Each prompt was sent to the model with temperature set to a moderate value. Very low
temperature makes outputs too deterministic and can hide distributional effects. Very high
temperature adds noise and makes parsing less reliable. The chosen setting balances variation
with coherence.

For each prompt pair, multiple responses were generated. Responses were discarded if they
failed to answer the probe, contained fewer than a minimum number of tokens, or copied a
large fragment of the context. The remaining responses were parsed and converted into
construction counts.

The primary outcome is the difference in normalized construction rate between the aligned and
control conditions. Secondary outcomes include response length, parse failure rate, and
qualitative error categories. As in many model-evaluation settings, the analysis treats
performance estimates as noisy signals rather than final judgments #cite("yao2023predictinggeneralizationperformancecorrectness").

#figure(caption: [Distribution of response lengths after filtering.])[
  #sample-figure(
    [Most responses fall between 90 and 180 tokens],
    [The histogram is intentionally represented schematically in this sample document.]
  )
] <fig:lengths>

== Annotation Pipeline

After generation, each response passes through an annotation pipeline that turns text into
counts of syntactic events. The pipeline has four stages. First, responses are normalized by
removing system artifacts and repeated whitespace. Second, each sentence is parsed with a
dependency parser. Third, construction-specific detectors collect candidate spans. Finally,
aggregate counts are written to a table keyed by prompt pair, condition, construction family,
and model run.

The pipeline is deliberately conservative. It is better to miss a few borderline cases than to
inflate the alignment signal with false positives. For example, a passive detector should not
count every past participle as passive. It should require evidence for an auxiliary and a
dependency relation compatible with passive voice. Similarly, a relative-clause detector should
distinguish finite relatives from ordinary complement clauses where possible.

=== Normalization

Normalization is small but important. Model responses often contain leading discourse markers
such as "Sure" or "Here is a concise explanation". These phrases are not removed, because they
are part of the generated response. However, boilerplate that repeats the prompt or explicitly
describes the task is filtered. The goal is to preserve natural syntax while excluding obvious
failures of the generation protocol.

Responses are also segmented into sentences. Sentence segmentation is treated as a diagnostic
rather than a ground truth operation. If a response contains an unusually high number of
fragments, the parser may still produce an analysis, but the response is flagged for later
inspection.

=== Detector Rules

Each construction family is represented by a small set of detector rules. These rules combine
parser labels with lexical and morphological cues. A passive construction, for instance, is
counted when the parser marks a passive auxiliary or passive subject relation. A relative clause
is counted when a clausal modifier is introduced by a relative marker or has the dependency
shape expected for a relative clause.

==== Passive Voice

Passive voice is the most reliable construction in the sample because the parser usually marks
the relevant dependencies explicitly. The detector counts canonical passives such as "the
summary was revised" and ignores adjectival participles unless there is an auxiliary or subject
configuration suggesting an eventive reading.

===== Ambiguous participles

Ambiguous participles are handled cautiously. A phrase such as "the revised summary" is not
counted as passive, because it functions as an attributive modifier. A phrase such as "the
summary was revised by the assistant" is counted, because the auxiliary and optional by-phrase
make the passive analysis clear. This level-5 heading is included to exercise paragraph-style
heading behavior in the template.

==== Relative Clauses

Relative clauses are harder to detect because generated text often omits explicit relative
markers. The detector therefore distinguishes explicit relatives, such as "the file that failed",
from reduced relatives, such as "the file stored on the server". Only explicit relatives are used
in the main analysis. Reduced relatives are recorded separately and inspected qualitatively.

The separation keeps the primary metric easier to interpret. It also avoids conflating relative
clauses with ordinary postnominal modifiers. This is especially useful in technical prose, where
postnominal participial phrases are frequent.

#figure(kind: table, caption: [Detector decisions for ambiguous examples.])[
  #table(
    columns: (2.2fr, 1.2fr, 2fr),
    inset: 6pt,
    table.header([Example], [Decision], [Reason]),
    [the summary was revised], [Count], [Auxiliary plus passive participle],
    [the revised summary], [Skip], [Attributive participle],
    [the file that failed], [Count], [Explicit relative marker],
    [the file stored locally], [Inspect], [Reduced relative or modifier],
  )
] <tab:detectors>

=== Reliability Checks

The annotation pipeline includes several reliability checks. A random sample of responses is
inspected manually, and the manual notes are compared with detector outputs. The goal is not
to produce a full gold standard, but to identify systematic detector failures before interpreting
the aggregate results.

The most common errors involve sentence boundaries and reduced clauses. Sentence-boundary
errors can make a construction appear to span more material than it actually does. Reduced
clauses can be hard to distinguish from adjectival modifiers. These cases are flagged rather
than silently folded into the main counts.

#figure(caption: [Manual validation workflow for parser-derived counts.])[
  #sample-figure(
    [Sample responses -> manual notes -> detector comparison -> revised filters],
    [The workflow is lightweight, but it catches recurring parser and segmentation errors.]
  )
] <fig:validation>

== Dataset Summary

The final sample contains prompt pairs distributed across four construction families. Each pair
contributes one aligned condition and one control condition. Multiple responses are generated
for each condition, which makes it possible to estimate variation across runs as well as across
prompt items.

The dataset is intentionally small enough to inspect. Large automatically generated datasets
can hide annotation failures, while very small datasets make effect estimates unstable. The
sample size used here is meant to balance those concerns for a thesis-scale experiment.

#figure(kind: table, caption: [Mock dataset size after filtering.])[
  #table(
    columns: (1.5fr, 1fr, 1fr, 1.2fr),
    inset: 6pt,
    table.header([Construction], [Pairs], [Responses], [Filtered]),
    [Passive voice], [40], [480], [22],
    [Relative clauses], [40], [480], [31],
    [Complement clauses], [32], [384], [19],
    [PP sequences], [32], [384], [27],
  )
] <tab:dataset>

= Results

The results show consistent but construction-dependent alignment. Passive voice and relative
clauses produce the clearest effects. Complement clauses show a smaller effect, and
prepositional phrase sequences are noisy. These differences are consistent with the intuition
that some constructions are easier for the model to track and reproduce than others.

== Main Alignment Effects

The largest effect appears for passive voice. In passive-rich contexts, the model produces more
passive clauses in the probe response than in matched active contexts. The difference is not
large in absolute terms, but it is stable across prompt families.

Relative clauses show a similar pattern. Contexts with repeated relative clauses increase the
rate of relative clauses in later responses. Qualitative inspection suggests that the model often
uses relative clauses to maintain the explanatory style of the context.

#figure(kind: table, caption: [Estimated alignment effects by construction family.])[
  #table(
    columns: (1.6fr, 1.2fr, 1.4fr, 1.4fr),
    inset: 6pt,
    table.header([Construction], [Effect], [95% CI], [Interpretation]),
    [Passive voice], [+3.8 pp], [[+2.1, +5.4]], [Clear],
    [Relative clauses], [+2.9 pp], [[+1.0, +4.6]], [Clear],
    [Complement clauses], [+1.2 pp], [[-0.1, +2.5]], [Weak],
    [PP sequences], [+0.6 pp], [[-1.4, +2.2]], [Unclear],
  )
] <tab:effects>

The table is intentionally modest. The important point is not that the model becomes a mirror
of the prompt. Rather, the distribution shifts. In an interactive setting, such shifts can
accumulate across turns and contribute to the perceived style of the system.

== Persistence Across Turns

Alignment decays with distance, but it does not vanish immediately. When one filler turn is
inserted between the context and the probe, the passive effect remains visible. With three filler
turns, the effect becomes smaller and less reliable. Relative clauses show a similar but slightly
faster decay.

This pattern suggests that syntactic information is retained as part of the recent dialogue
state. It is not merely a token-local continuation effect. At the same time, the decay indicates
that syntax competes with newer content and instructions.

#figure(caption: [Schematic decay of alignment over intervening turns.])[
  #sample-figure(
    [0 turns: strong | 1 turn: moderate | 3 turns: weak],
    [The trend illustrates decreasing influence as additional material enters the context.]
  )
] <fig:decay>

== Conclusion

This thesis has examined syntactic long-term alignment in large language models. The results
show that prior syntactic context can influence later model output, especially for passive voice
and relative clauses. The effect is moderate, construction-dependent, and sensitive to the
distance between context and probe.

The broader conclusion is that prompt form matters. Language models respond not only to the
meaning of a prompt but also to its linguistic shape. For evaluation, this means that benchmark
prompts should be treated as stylistic artifacts as well as task descriptions. For design, it means
that examples can guide models in subtle ways that explicit instructions do not capture.

Future work should test naturally occurring dialogues, additional languages, and more precise
syntactic annotations. It should also ask when alignment improves interaction and when it
amplifies undesirable style. Understanding this balance will help us build systems that adapt
without blindly inheriting every pattern in their context.




#print-lst-bibliography()
