#import "lst.typ": *



#show: doc => lst(
  title: [Analysing Syntactic Long-term Alignment in Large Language Models],
  author: [Florian Kandra],
  matriculation-number: [12345],
  supervisors: ([Prof. Dr. Alexander Koller], [Prof. Dr. Vera Demberg]),
  date: [31.12.2024],

  abstract: [
    This thesis explores the effects of long-term syntactic alignment in Large Language Models
    (LLMs). An approach by Reitter (2008) was adapted to analyze alignment effects between
    speakers. The analysis replicates previous findings from Reitter & Moore and was validated
    against baseline data. Additionally, new datasets created with OpenAI’s GPT-4o provide a
    basis for analyzing conversational texts generated by LLMs, addressing a gap in existing
    research for evaluating LLM-generated texts.

    The findings reveal that syntactic alignment occurs in LLMs over extended periods. A second
    analysis further explores how the process of alignment evolves throughout a conversation,
    showing that LLMs consistently adjust their syntax, with the largest changes occurring early
    on.
    
    These results indicate that LLMs are not only influenced by the semantics of instructions,
    but also by the syntax present in their context. LLM responses are shaped not only by the
    vector representations of tokens in their prompts, but also by the linear order in which those
    tokens appear.
  ],

  acknowledgments: [
    First and foremost, I want to thank my incredible supervisors, Prof. Dr. Koller and Prof. Dr.
    Demberg, who guided me throughout an extended period and provided support no matter
    where I was. Your thoughtful and precise feedback was crucial, always helping me to spot the
    next steps. Thank you for your enduring support and all the lively discussions along the way!

    I also want to give a special shoutout to my friends, especially Felix Cagliotti, who took the
    time for long brainstorming sessions despite his busy schedule. Your early-stage support and
    creative ideas were a great way to get started!

    To my flatmates -- thank you for taking time off me by reducing my cooking workload. And
    to my family -- thank you for baring me as the hermit that I was, especially during Christmas
    time. A big thanks to my dad for always being there to discuss my research challenges, my
    brother for his incredibly quick and spot-on ideas and my mom for keeping my mind light
    and stress-free.

    Lastly, a big hug to our cat Minka, who somehow managed to stay with us through at least
    half of my work -- offering purrs and cuddles when I needed them most!
  ],

  doc
)


= Introduction

#lorem(50)


= Background

#lorem(50)

== Related Work

=== Previous Work 1

#lorem(50)

=== Previous Work 2

#lorem(50)



=== Previous Work 3

#lorem(50)